import { Link } from "react-router";
import { MarketingLayout } from "@/components/MarketingLayout";

export default function Terms() {
  return (
    <MarketingLayout>
      <article className="mx-auto max-w-3xl px-4 py-16 sm:px-6">
        <h1 className="text-3xl font-bold tracking-tight">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Last updated: February 22, 2026
        </p>

        <div className="prose prose-neutral mt-8 max-w-none dark:prose-invert [&_h2]:mt-8 [&_h2]:text-xl [&_h2]:font-semibold [&_h3]:mt-6 [&_h3]:text-lg [&_h3]:font-medium [&_p]:mt-3 [&_p]:leading-relaxed [&_p]:text-muted-foreground [&_ul]:mt-3 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:text-muted-foreground [&_li]:mt-1">
          <h2>1. Service Description</h2>
          <p>
            Memogenesis (&quot;the Service&quot;) is an AI-powered flashcard generation
            platform operated by Luis W. Gordon (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;). The
            Service allows you to generate, manage, and export flashcards for
            use with Anki and other spaced repetition systems.
          </p>

          <h2>2. Account Responsibilities</h2>
          <p>
            You are responsible for maintaining the security of your account
            credentials. You must provide a valid email address for account
            creation. You may not share your account or create multiple accounts
            to circumvent usage limits.
          </p>

          <h2>3. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>
              Use the Service to generate content that is illegal, harmful, or
              violates third-party rights.
            </li>
            <li>
              Attempt to reverse engineer, exploit, or disrupt the Service.
            </li>
            <li>
              Submit copyrighted content without authorization from the rights
              holder.
            </li>
            <li>
              Use automated tools to access the Service beyond its intended API.
            </li>
            <li>
              Resell or redistribute generated cards commercially without
              attribution.
            </li>
          </ul>

          <h2>4. Billing & Payments</h2>
          <p>
            Paid plans are billed monthly via Stripe. Prices are listed in EUR.
            Overage charges are calculated at the end of each billing cycle
            based on your plan&apos;s per-card rate. You can cancel your
            subscription at any time; access continues until the end of your
            current billing period.
          </p>
          <p>
            We reserve the right to change pricing with 30 days&apos; notice.
            Price changes do not affect the current billing period.
          </p>

          <h2>5. Intellectual Property</h2>
          <h3>Your content</h3>
          <p>
            You retain all rights to content you submit and cards you generate.
            By using the Service, you grant us a limited license to process your
            content solely for the purpose of providing the Service.
          </p>
          <h3>AI-generated content</h3>
          <p>
            Flashcards generated by the Service are created using AI (Claude by
            Anthropic). While we strive for accuracy, AI-generated content may
            contain errors. You are responsible for reviewing generated cards
            before use. We make no warranties about the accuracy, completeness,
            or suitability of AI-generated content.
          </p>
          <h3>Our service</h3>
          <p>
            The Service, its design, code, and documentation are owned by Luis
            W. Gordon. Nothing in these terms grants you rights to our
            intellectual property beyond using the Service as intended.
          </p>

          <h2>6. Data Processing</h2>
          <p>
            Your use of the Service is subject to our{" "}
            <Link
              to="/privacy"
              className="font-medium text-foreground underline underline-offset-4"
            >
              Privacy Policy
            </Link>
            . By using the Service, you consent to the collection and
            processing of data as described therein.
          </p>

          <h2>7. Limitation of Liability</h2>
          <p>
            The Service is provided &quot;as is&quot; without warranties of any kind. To
            the maximum extent permitted by law, we are not liable for any
            indirect, incidental, consequential, or punitive damages arising
            from your use of the Service, including but not limited to loss of
            data, loss of revenue, or interruption of service.
          </p>
          <p>
            Our total liability for any claim related to the Service shall not
            exceed the amount you paid us in the 12 months preceding the claim.
          </p>

          <h2>8. Termination</h2>
          <p>
            You may close your account at any time via the Settings page. We may
            suspend or terminate your account for violation of these terms, with
            notice where practicable. Upon termination, your data will be
            deleted in accordance with our Privacy Policy retention schedule.
          </p>

          <h2>9. Governing Law</h2>
          <p>
            These terms are governed by the laws of the Republic of Panama. Any
            disputes shall be resolved in the courts of Panama City, Panama.
          </p>

          <h2>10. Changes to These Terms</h2>
          <p>
            We may update these terms from time to time. Material changes will
            be communicated via email or in-app notification at least 30 days
            before taking effect. Continued use after changes constitutes
            acceptance of the updated terms.
          </p>

          <h2>11. Contact</h2>
          <p>
            For questions about these terms, contact us at
            legal@memogenesis.com.
          </p>
        </div>
      </article>
    </MarketingLayout>
  );
}
